{% set version = "9.10.0" %}

package:
  name: medcoupling
  version: '{{ version }}'

source:
  - fn: 'medcoupling_{{ version }}.tar.gz'
    url: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git;a=snapshot;h=V{{ version.replace('.', '_') }};sf=tgz
    sha256: 02087a4e59ffcdab6fc68460ffd86b03a80b5c0faa695b0bfb2142f1d0d3e5ea
  - fn: 'config_{{ version }}.tar.gz'
    url: https://git.salome-platform.org/gitweb/?p=tools/configuration.git;a=snapshot;h=V{{ version.replace('.', '_') }};sf=tgz
    folder: deps/config
    sha256: d58f6749514ce49b00590a96d6dc9090a76a07c13690e2453403643afb40346c


build:
  skip: True  # [osx]
  detect_binary_files_with_prefix: true
  # string: py{{ CONDA_PY }}_mpi_{{ mpi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}   # [mpi != "nompi"]
  # string: py{{ CONDA_PY }}_nompi_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}           # [mpi == "nompi"]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                                      # [not win]
    - ninja                                     # [win]
    - cmake
    - swig >=4.0.2

  host:
    - python
    - numpy
    - libboost-devel
    - zlib
    - hdf5
    - libxml2
    - libmed
    - petsc                                     # [mpi != 'nompi']
    - {{ mpi }}                                 # [mpi != 'nompi']

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}                                 # [mpi != 'nompi']

test:
  imports:
    - medcoupling
    - MEDRenumber
    - MEDCouplingRemapper
    - MEDLoader
    - MEDPartitioner
    - MEDCoupling  # [linux]
    - MEDCouplingCompat  # [win or osx]

about:
  home: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'The MEDCoupling tool gathers several powerful functionalities around the input and output data of simulation codes (meshes and fields mainly)'
  description: |
    The MEDCoupling tool gathers several powerful functionalities around the input and output data of simulation codes (meshes and fields mainly)
  doc_url: https://docs.salome-platform.org/latest/dev/MEDCoupling/developer/index.html
  dev_url: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git;a=summary

extra:
  recipe-maintainers:
    - Krande
